stitchesjs/stitches

packages/css/README.md
=> Fix typo in CSS readme

packages/css/src/index.ts, packages/styled/src/index.ts
Just some minor things I noticed while reading through the code.
=> Minor refactor

packages/styled/README.md
=> fix: remove duplicate export

packages/styled/src/index.tsx
=> Fix not forwarding ref in styled components

package-lock.json, packages/css/src/index.ts, packages/css/src/types.ts, packages/css/src/utils.ts, packages/css/tests/index.test.ts, packages/styled/src/index.tsx
Okay,
So this PR should contain:
1. Breakpoints as discussed here: https://github.com/modulz/stitches/issues/86#issuecomment-675590197
2. Ampersand support: https://github.com/modulz/stitches/issues/60
3. Pseudo presedence as mentioned here: https://github.com/modulz/stitches/issues/83#issuecomment-673942355
I wrote simple tests for these, but looks good so far 😄
=> Breakpoints, inline media queries, ampersand and pseudo presedence

packages/css/src/index.ts, packages/css/src/shorthand-parser/index.ts, packages/css/src/shorthand-parser/value-tokenizer.ts, packages/css/src/utils.ts, packages/css/tests/index.test.ts, packages/css/tests/shorthand-parser.test.ts, packages/css/tsconfig.json, packages/tailwind/src/utils.ts
Preparation for an alpha release
=> Fixes linting issues

packages/css/src/index.ts, packages/css/tests/index.test.ts
=> fix undfined values

packages/css/src/index.ts, packages/css/src/types.ts, packages/css/tests/index.test.ts
=> Fix nesting selectors

packages/core/src/index.ts, packages/core/src/types.ts, packages/core/tests/index.test.ts
=> Revert theme function to previous functionality

packages/core/src/shorthand-parser/index.ts, packages/core/tests/shorthand-parser.test.ts
=> Fix number values match bug

packages/core/src/index.ts, packages/core/src/types.ts, packages/core/tests/index.test.ts, packages/react/src/index.tsx
Just removed the leftovers of "utility first". Should improve typing speed a little bit 😄
=> remove utility first

packages/core/src/constants.ts, packages/core/src/index.ts, packages/core/tests/index.test.ts, packages/core/tests/ssr-only.test.ts
=> Add ssr only tests and fix composition cache

packages/react/src/index.tsx
Before and After explanation:
https://streamable.com/llq74k
=> update props of a styled component for better DX

packages/core/src/css-types.ts
@peduarte similar to https://github.com/modulz/stitches/commit/767eda6f25cb6c3e4d1e4c382d831f85173036f6
=> Add number to flexBasisProperty type

packages/react/src/index.tsx, packages/react/tests/index.test.tsx
=> Return string based className from styled components in the react package

packages/core/src/shorthand-parser/index.ts, packages/core/src/utils.ts, packages/core/tests/index.test.ts, packages/core/tests/shorthand-parser.test.ts
=> Parse flex shorthand

packages/core/src/index.ts, packages/core/tests/index.test.ts, packages/core/tests/ssr-only.test.ts
**Two new things:**
- ampersand should now work like in other css in js library when nested - fixes #233
- comma-separated rules will work and be scoped correctly
Please it a good old street test and let me know if you find any edge case that needs handling
The tests diff is a bit large as the selectors got reworked which caused the hashing function to return a different hash but other than that I've added new tests cases to test the new functionality
=> Feature/comma separated rules & fixed ampersand support

packages/core/src/shorthand-parser/index.ts, packages/core/tests/index.test.ts, packages/core/tests/shorthand-parser.test.ts, packages/react/tests/__snapshots__/index.test.tsx.snap
This PR fixes the parsing of `flex` property
=> Update `flex` parser

packages/react/src/index.tsx, packages/react/tests/__snapshots__/index.test.tsx.snap, packages/react/tests/index.test.tsx
This PR fixes class name composition. I've added a couple of extra tests to catch this in the future.
Closes #256
=> Fix and test class name composition

packages/react/src/index.tsx
compundVariantsObject -> compoundVariantsObject
=> Fix typo in code

packages/react/src/index.tsx
Had to bring back the overloads to get this fixed 
Fixed #43
=> Fix events types on Styled components

packages/react/package.json
Alternatively could set this to `"react": ">=16.13.1"`
=> Allow react v17 peerDependency

packages/core/tests/types.test.ts, packages/core/types/css-types.ts, packages/core/types/index.d.ts, packages/react/tests/types.test.tsx, packages/react/types/index.d.ts, tsconfig.json
@jonathantneal  just an FYI, this only updates types so I'm merging with your branch directly.
=> Abdul.types.5

packages/core/types/index.d.ts, packages/react/tests/types.test.tsx
@jonathantneal Just an FYI as I modified the core types
=> Fix Stitches CSS

packages/core/src/index.js, packages/core/types/index.d.ts, packages/react/tests/types.test.tsx
just exposed the config as Pedro and I discussed
also updated the types for the utils in the config
=> Expose config and update utils

packages/core/types/index.d.ts, packages/react/tests/types.test.tsx
=> type token

packages/core/types/index.d.ts, packages/react/tests/types.test.tsx
Just a type fix for the inline config inside the utils
=> Types fix util token type

packages/core/src/defaultThemeMap.js
Closes https://github.com/modulz/stitches/issues/376
=> Map `textDecorationColor` to `colors` scale

packages/core/src/createGetComputedCss.js, packages/core/tests/universal-tokens.js
This PR adds the ability to use negative tokens like `-$sp1`.
This resolves #370.
=> feat: support negative tokens

packages/core/tests/types.test.ts, packages/core/types/index.d.ts
=> Fix not being able to compose css calls 

packages/core/types/css-types.ts
Resolves https://github.com/modulz/stitches/issues/445
=> Add `string` to line-clamp typing

packages/core/src/createGetComputedCss.js, packages/core/tests/universal-numeric-values.js
This PR fixes an issues where certain numeric values were or were not being px-ified.
=> fix: numeric values

packages/core/src/createGetComputedCss.js, packages/core/tests/component-empty-variants.js
This PR fixes an issue with empty variant nesting.
=> fix: empty variant nesting

packages/core/src/defaultThemeMap.js, packages/core/types/index.d.ts
=> Add gridTemplateColumns/Rows to sizes theme token

packages/core/src/defaultThemeMap.js
=> Map outline to colors

packages/core/src/createStringify.js
This PR adds a vendor prefix to `box-decoration-break`.
=> Feature: add box-decoration-break vendor prefix polyfill

package.json
Also to test that #510 works 😄
=> Remove `version` from root `package.json`

packages/core/tests/issue-999.js, packages/stringify/src/index.js
This PR resolves an issue where repeated local tokens would not be correctly. transformed.
Resolves #519
=> Fix: Support repeated local tokens

packages/core/src/createStringify.js
since safari need `-webkit` prefix
=> feat: add backdrop-filter polyfill

packages/core/src/createStringify.js, packages/core/src/index.js, packages/core/src/stringify/transformDeclarationValueTokens.js, packages/core/tests/component-utils-and-types.js, packages/core/tests/issue-999.js, packages/core/tests/theme.js, packages/core/tests/universal-serialization.js, packages/core/tests/universal-tokens.js, packages/react/tests/component-css-prop-react.js, packages/react/tests/component-repeated-variants.js, packages/react/tests/universal-serialization.js
This PR changes how token prefixing works so that the default `sx` prefix is ignored.
=> Fix token prefixing

packages/core/types/create-css.d.ts, packages/core/types/css-util.d.ts, packages/core/types/index.d.ts, packages/core/types/styled-component.d.ts, packages/react/types/css-util.d.ts, packages/react/types/index.d.ts, packages/react/types/styled-component.d.ts, tsconfig.json
Resolves #678
```tsx
import type * as Stitches from '@stitches/core'
const blue: Stitches.CSS = {
color: 'Blue',
/* suggestions */
'&:hover': {
color: 'DarkBlue',
/* suggestions */
}
}
const text: Stitches.CSS = {
...blue,
fontSize: 'larger',
/* suggestions */
'&:hover': {
fontWeight: 700,
/* suggestions */
}
}
```
```tsx
import type * as Stitches from '@stitches/react'
const blue: Stitches.CSS = {
color: 'Blue',
/* suggestions */
'&:hover': {
color: 'DarkBlue',
/* suggestions */
}
}
const text: Stitches.CSS = {
...blue,
fontSize: 'larger',
/* suggestions */
'&:hover': {
fontWeight: 700,
/* suggestions */
}
}
```
---
Resolves #679
```tsx
import type * as Stitches from '@stitches/react'
import { createCss } from '@stitches/react'
const { css, styled } = createCss()
type ComponentProps = { …
```
=> Resolve TS issues in canary

README.md
=> Create community section in README

packages/core/src/features/css.js, packages/core/tests/component-variants.js, packages/core/tests/issue-725.js, packages/react/tests/component-variants.js
Fixes #725 
Codesandbox with the fixed issue: https://codesandbox.io/s/stitches-ci-cra-forked-19s9j
=> Fix: Multiple of the same variants didn't applied properly on responsive styles 

packages/core/src/features/css.js, packages/react/tests/issue-671-forwardRef.js
Add a fix and a testcase for https://github.com/modulz/stitches/issues/671#issuecomment-974641074
=> Issue 671 forward ref case

packages/core/src/sheet.js
Hi! :wave: 
I was hit by a bug with checking access for `cssRules` property on existing CSS style or link tags: https://github.com/modulz/stitches/issues/756 It was a real problem for me as I'm introducing Stitches to my project (it uses existing styles for other parts of the system) and we rely on Storybook (which renders components in an iframe) to get the UI elements right.
To avoid having problems I propose to improve how Stitches check for access to `cssRules` property on `CSSStyleSheet` objects to also include a try to access them and bail out if we catch an exception based on how this object should behave: https://drafts.csswg.org/cssom/#the-cssstylesheet-interface
I decided to keep earlier check as it should be easier and faster to process in most cases (as it is working in …
=> Improve check for cssRules access

packages/react/types/css.d.ts
add types to size-adjust, ascent-override;
=> Fix missing types

packages/core/src/convert/toCssRules.js, packages/core/src/convert/toPolyfilledValue.js, packages/core/tests/universal-autoprefixer.js, packages/core/tests/universal-numeric-values.js
Updating the polyfill and fixing the tests for https://github.com/stitchesjs/stitches/pull/1051
Closes https://github.com/stitchesjs/stitches/pull/1097
=> Fix tests and update polyfill

packages/core/src/convert/toTokenizedValue.js, packages/core/tests/issue-986.js
Fixes #986 
Updated regex to parse URL links, added test cases.
=> Fix toTokenizedValue() execution with URL values
