packages/css/tests/index.test.ts
I couldn't find the correct place to fix the test. It would be cool if this was supported without having to `ts-ignore`
=> Add failing test for shorthand conditional compose(cond && token)

packages/styled/src/index.tsx
Before this fix, the css prop would get passed to the actual dom element so this fixes it so that it doesn't show up on the dom just like variants.
=> Prevent css prop from appearing on the dom

package.json, packages/core/package.json, packages/react/package.json, tsconfig.build.json
Yesterday I added the types field because I saw that the types weren't working in codesandbox so I thought it was a global thing but today with more testing I found out that this issue is unrelated as I tested so many different formats of the type files and non of them worked on codesandbox but they worked for me locally and I was able to build design systems using the same published version that codesandbox wasn't able to read.
I got curious and looked at the network tab to see how codesandbox is querying types and noticed that there were a few errors in there related to the publish package as the requests sent to the codesandbox servers were throwing errors so will do a bit more research then open an issue there.
I'm suspecting that this might be with the types of structure that …
=> cleanup types

packages/core/src/index.ts, packages/core/tests/index.test.ts, packages/react/tests/__snapshots__/index.test.tsx.snap, packages/react/tests/index.test.tsx
@peduarte This will fix #94 by making nested breakpoints override breakpoints with lower nesting as we've discussed before.
also, this improves testing for styled-components to include media queries styles (see `index.test.tsx.snap` for an example) and with this fixed, the structure should be in place to test styled-components so this in addition to the work that we did a few days ago around testing and building should fix #75
=> Add config breakpoints and improve tests

packages/core/src/shorthand-parser/index.ts, packages/core/src/utils.ts, packages/core/tests/index.test.ts, packages/core/tests/shorthand-parser.test.ts
* Added support for text-decoration shorthand. Now we can pass in values like
```
textDecoration: underline dotted red;
```
or
```
textDecoration: underline overline dotted gray400;
```
* Also added support for text-decoration-thickness in short hand properties 
```
textDecoration: underline overline dotted gray400 5px;
```
* Tests updated for all of the above changes
Using this doc as a reference
https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration
Fix https://github.com/modulz/stitches/issues/142
=> feat: added support for text decoration shorthand and other long hand properties

.codesandbox/ci.json
=> Setup CodeSandbox CI

packages/core/src/index.ts
Since I know `window` object exists on Deno and it has `Deno` object within it, I added a check based on that.
Of course the question is how to test this effectively. 😄 
Closes #199.
=> fix: Fix check against Deno

packages/core/src/index.ts, packages/core/tests/index.test.ts, packages/core/tests/ssr-only.test.ts
=> fix: Close keyframe block on getStyles

packages/core/src/index.ts, packages/core/src/types.ts, packages/core/src/utils.ts, packages/core/tests/index.test.ts, packages/core/tests/ssr-only.test.ts
Fixes #185
This PR:
- ensures that `css.global` are server rendered
- ensures that `css.keyframes` are server rendered
Breaking change:
In order to be able to inject global styles, we need to make that a function.
```jsx
const globalStyles = css.global({})
// call it
globalStyles()
```
in React
```jsx
const globalStyles = css.global({})
const App = () => {
// call here
globalStyles()
return <div/>
}
```
We could provide a nicer API, maybe a hook, in `@stitches/react`
=> Global style keyframes injection

packages/core/src/index.ts, packages/core/src/types.ts, packages/core/tests/index.test.ts
=> Simplify utils API

packages/react/src/index.tsx
=> Fix TS types for variant composition

packages/core/src/css-types.ts, packages/core/src/types.ts, packages/core/tests/index.test.ts
Taking over from #116 
This PR adds a strict mode feature, originally proposed by @fgnass 
Strict mode is `false` by default.
I also did a review of the CSS Types, which closes #48. For example, this allows numbers in `margin` properties, since internally we convert them to `px`. 
---
**Important note**
When `strict: true` shorthands have a stricter syntax:
AFAIK its not possible to type strings that can contain multiple values. 
Unless, somehow, we create all the possible combinations of all tokens? (sounds like a terrible, terrible idea)
Say you have 4 space tokens: $1, $2, $3, $4
And you wanna add margin on all sides, you can do:
margin: "$2" // this passes validation, because its a single value in a string and its a token 
Now you wanna set margin top/bottom and margin left/right …
=> Strict mode and review CSS Types

packages/core/src/shorthand-parser/index.ts, packages/core/src/utils.ts, packages/core/tests/index.test.ts, packages/core/tests/shorthand-parser.test.ts
This PR converts `gap` to `rowGap` and `columnGap` - taking into account tokens.
Closes #224
=> Parse `gap` shorthand

package.json, yarn.lock
Doesn't appear that the npm package [`dts-bundle`](https://github.com/TypeStrong/dts-bundle) is used in the project. 
Can we remove this?
=> chore: remove dts-bundle npm package

jest.config.base.js, jest.config.js, package.json, packages/core/jest.config.js, packages/core/package.json, packages/react/jest.config.js, packages/react/package.json, yarn.lock
- allows Jest to be run from the root of the project.  As Jest supports [`projects`](https://jestjs.io/docs/en/configuration#projects-arraystring--projectconfig) we can use that to run Jest from root of the project folder. _"This is great for monorepos"_. 
- Also allows the usage of [VSCode Extension Jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) to work without custom configuration.
- removed what appears to be a legacy node version logic in [`jest.config.base.js`](https://github.com/modulz/stitches/compare/canary...andykenward:jest-config?expand=1#diff-66d3521f5e9f81934077fdd6653d0901L1-L18). We can use the projects tsconfig.json. Perhaps we need to define the package.json [`engines`](https://docs.npmjs.com/files/package.json#engines) for what version of …
=> refactor: jest configuration

packages/core/src/index.ts, packages/core/tests/index.test.ts
This changes the internal [`hyphenAndVendorPrefixCssProp`](https://github.com/modulz/stitches/blob/v0.0.3-canary.3/packages/core/src/index.ts#L264-L281) function to a prevent `isVendorPrefixed` from returning a false positive when evaluating a custom property. It also adds a custom property test that would currently fail.
A custom property like `--whatever` is transformed into `---whatever`.
This is caused by a vendor prefix check that checks for uppercase letters and falsely matches dashes.
```js
const isVendorPrefixed = cssProp[0] === cssProp[0].toUpperCase()
// ( `-` === `-`.toUpperCase() ) === true // 😿🧻
```
A custom property like `--whatever` remains `--whatever`.
The vendor prefix check would explicitly check for an uppercase letter.
```js
const isVendorPrefixed = …
```
=> Preserve Custom Properties

packages/react/src/index.tsx
Adds ExtractVariantProps generic util that allows extracting the variant props out of stitches components
Allows React.ComponentProps to work with stitches components - Fixes #248
=> Add way to extract props & variants types

packages/react/tests/__snapshots__/index.test.tsx.snap, packages/react/tests/index.test.tsx
I wanted to fix #253 but it was already working in latest canary 🤩
So I added a test for it.
=> test(#253): add test for boolean compound variables

packages/core/tests/types.test.ts, packages/core/types/index.d.ts, packages/react/tests/types.test.tsx, packages/react/types/index.d.ts
- Fixes polymorphic types
- Fixes losing variants after extending stitches components 
- Fixed type boolean casting variant names to strings (@jonathantneal FYI, had to create a new type for it in core)
- Fixed variants props erroring when the element also has a variant with the same name
@jonathantneal I noticed that you've created a new CSS type `LessInternalCSS` to fix the CSS props as variants but I didn't start using it as I saw that it had a todo above it. let me know if it's safe to use so that I update the react package to use this fixed type.
@peduarte in the react package, there is a `types.tests.tsx` file in the tests folder which has a bunch of ts tests for the polymorphic stuff that you could use during testing. 
Please use it for your testing and if you find any bugs, please …
=> Update react types

packages/core/types/index.d.ts, packages/react/tests/types.test.tsx, packages/react/types/index.d.ts
@jonathantneal nothing in here just exporting the types so that typescript is able to compile them correctly when destructuring
=> export all the types

packages/core/tests/types.test.ts, packages/core/types/index.d.ts, packages/react/tests/types.test.tsx, packages/react/types/index.d.ts
=> Fix compounds and default variants in react

packages/core/types/index.d.ts
This PR changes morph variant typing to support boolean values, which are naturally typed as a kind of union of `true` and `false`.
When an author creates variants with values of `true` or `false`, they actually exist as string values `"true"` or `"false"`. Currently, we support their targeting them with literal boolean values using _morph variants_.
However an author creates a variant with only one boolean value, then TypeScript would only allow that literal boolean value. However, since boolean values are naturally a kind of union of `true` or `false`, this causes TypeScript to flag the perfectly valid boolean value.
=> Fix: Support looser morph variants

packages/core/types/css-types.ts
This PR updates the browser compatibility for gap properties and adds the legacy `gridRowGap` and `gridColumnGap` properties.
=> Update browser compatibility for gap properties and add legacy gap properties

packages/core/src/Object.js, packages/core/src/index.js, packages/react/src/index.js, packages/react/tests/serialization.js
This PR updates both the core and react releases to add css on reference, so that referencing a theme like `className={theme}` would automatically push the theme CSS into the stylesheet. This PR also rolls back a change to `theme()`, which started returning a selector, but will now return a class name as it did before.
=> feat: always add css on reference, implicitly return className on theme

packages/core/src/index.js, packages/core/types/index.d.ts, packages/react/src/index.js, packages/react/types/index.d.ts
This PR changes the exports of `@stitches/core` and `@stitches/react` so that the `createCss` default export is also a named export.
Examples:
```js
import { createCss } from '@stitches/core'
```
```js
import { createCss } from '@stitches/react'
```
=> Feature: Add a named createCss export

packages/core/src/index.js, packages/core/tests/variants.js
This PR fixes an issue where responsive classes would still receive their unresponsive class, resulting in the wrong styles being applied.
=> fix: responsive variants should not receive their unresponsive class

.bin/build-watch.js, .bin/test-watch.js, package.json, packages/core/src/index.js, packages/core/tests/variants.js
This PR fixes an issue where responsive variants would apply once.
It was caused by aggressive caching that would save the generated variant if it did not exist. However, if the responsive variant existed, it would not use it!
=> fix: issue where variants responsive would apply only once

package.json, packages/react/package.json
This PR changes the `package.json` of `@stitches/react` to reference a clearer range of supported React versions. This also adds `react` as a development dependency of the project.
=> fix: correct how the react peerDependency should be written

packages/core/src/index.js, packages/core/tests/as-prop.js
This PR changes how variant props do not fall through, so that `as` does.
=> fix: preserve props for variants named "as"

packages/react/types/index.d.ts
This PR fixes type inference in the factory function of`@stitches/react` by adding several missing type arguments.
Fixes https://github.com/modulz/stitches/issues/366.
=> Fix type inferred from the creator function in `@stitches/react`

packages/core/src/index.js, packages/core/tests/variants.js, packages/react/src/index.js, packages/react/tests/as-props.js
This PR fixes an issue where a default variant value would apply over the explicitly set value when it was used on its own. This also updates the variants test to be easier to read and update in isolation.
=> fix: issue where variants apply regardless

packages/core/types/css-types.ts
This PR removes unused CSS property types. Unused types are problematic because they cause type-checking to fail if you have the `noUnusedLocals` flag enabled in your `tsconfig.json`.
I also looked at https://github.com/frenic/csstype for reference and these types don't seem to be present there anymore either.
=> Remove unused types in `css-types.ts`

packages/core/src/index.js, packages/react/tests/variants.js
This PR changes variant values of `undefined` to use its corresponding `defaultVariant` value if it is available. This was a useful feature included prior to the v0.1.0 versions of stitches.
Resolves #385
=> fix: undefined variant value uses the default value

packages/react/src/index.js, packages/react/tests/components.js
This PR fixes an issue introduced in canary.3 where standard react components could not be extended. As with every step forward, this PR introduces tests to ensure this regression would not happen again.
Resolves  #387
=> fix: extending regular react components

packages/core/types/index.d.ts
This PR adds typing support for the `initial` condition, which resolves #374.
=> fix: initial condition not typed

packages/core/src/index.js
This PR fixes an issue where checking non-existent default variants throws an error.
This resolves #398
=> fix: issue checking non-existent default variants

packages/core/src/Array.js, packages/core/src/createGetComputedCss.js, packages/core/types/css-types.ts, packages/core/types/index.d.ts
This PR updates core to support array-values for at-rules like `@font-face` and `@import`, allowing authors to specify multiple imports or multiple font faces.
**Usage**:
```js
global({
'@import': [
`"some-styles.css"`,
`"more-styles.css"`,
],
'@font-face': [
{
fontDisplay: 'swap',
fontFamily: 'MyFont',
src: 'url(MyFontNormal.woff)',
},
{
fontDisplay: 'swap',
fontFamily: '"MyFont"',
fontStyle: 'italic',
src: 'url(MyFontItalic.woff)',
},
],
})
```
Resolves #396
=> feat: support global at-rule arrays

packages/core/src/getResolvedSelectors.js, packages/core/tests/nesting.js
This PR adds support for recursive nesting to Stitches. This will behave as CSS nesting is intended to behave per [spec](https://drafts.csswg.org/css-nesting/), likely making Stitches the very first CSS library to fully support this feature.
Here’s an example of complex, recursive nesting:
```js
const globalStyles = global({
'article p, article ul': {
margin: 0,
'& ~ &': {
marginTop: '2em',
}
}
})
const component = css({
'& p, & ul': {
margin: 0,
'& ~ &': {
marginTop: '2em',
}
}
})
```
In both rules, descendant paragraphs and unordered lists should not have any margin, except when they are proceeding siblings of each other that are also descendants of the same ancestor. 👀 
Resolves #372
=> Support recursive and complex nesting

packages/react/tests/types.test.tsx, packages/react/types/index.d.ts, tsconfig.json
This PR fixes autocompletion in the best way possible with the current limitation of how TS only shows auto-completion for the first overload.
this PR works by changing the interface that we create when we call `styled(T, {})` based on the value of T
**Two main interfaces used here:**
- so if T is a react component then the resulting typed interface is `StitchesComponentWithAutoCompleteForReactComponents`
- and if T is a Stitches component or a JSX intrinsic element then the resulting typed  interface will be `StitchesComponentWithAutoCompleteForJSXElements`
**How events will be typed:**
- events with the as prop will be typed if the as prop was a JSX intrinsic element
- events will be any if the as prop is a component or if the stitches component was extending another non-stitches …
=> Fix auto complete with polymorphism 

packages/react/src/index.js
This PR ensures that the CSS injected by `stitches/react` is in the same order as `stitches/core`
=> fix: ensure CSS always use the same order

packages/core/types/index.d.ts, packages/react/types/index.d.ts
This PR updates our typings to support boolean and numeric variant values when using TypeScript.
Examples:
```tsx
Test = styled("div", {
variants: {
defined: {
undefined: {}
},
strong: {
true: {}
},
weight: {
400: {},
},
},
defaultVariants: {
strong: true,
defined: void 0
},
compoundVariants: [
{
strong: true,
defined: undefined,
css: {}
}]
})
```
```tsx
<Test weight={500} />
```
Resolves #384
Resolves #403
=> fix: boolean & numeric type variant, default/compound variant support

packages/core/types/index.d.ts
This PR updates the typings to support numeric tokens in themes with TypeScript.
Example:
```tsx
import { createCss } from '@stitches/react'
const { styled, css } = createCss({
theme: {
fontWeights: {
light: 300,
regular: 400,
semibold: 600,
bold: 700,
},
},
})
```
Resolves #226
=> fix: support numeric tokens in themes

packages/react/types/index.d.ts
This PR adds typing support for components created using the `styled.ELEMENT_NAME` proxy in TypeScript.
Resolves #379
=> fix: typing for styled proxy

packages/core/types/index.d.ts
This PR updates the typescript typings for conditions so that using custom properties do not throw an error.
=> fix: allow custom props in conditions in TS

packages/react/types/index.d.ts
This PR fixes an issue autocompleting tokens in components created with the `styled.ELEMENT_NAME` proxy.
```tsx
const { styled } = createCss({
theme: {
colors: {
red: "tomato",
},
},
})
const Button = styled.button({
// autocompletes "$red"
backgroundColor: "",
})
```
Resolves #415
=> fix: typing for proxy elements

packages/core/types/index.d.ts
This PR updates the TypeScript `MorphVariant` and `StrictMorphVariant` utilities to fix an issue where certain number/string combinations would throw a TS error or fail to autocomplete.
Resolves #421
=> fix: issue with "morph" variants autocomplete and erroring

packages/core/src/index.js
This PR updates how comparisons are made in variants or compounds so that loosely matching primitive values will match as tho they were the same primitive type.
This resolves #424
=> fix: comparing variants with loosely matching primitive values

packages/core/src/index.js, packages/core/tests/component-variants.js, packages/react/tests/component-variants.js
This PR changes the `toString()`, `className`, and `selector` properties of a `css` or `style` component so that they return the root class name or selector, without the additional default variants applied.
=> fix: return plain classname or selector on toString

.bin/color.js, .bin/coverage.js, package.json
This PR adds code coverage benchmarking to the project, which will be extremely helpful in preventing regressions, identifying weakly enforced areas within our code, and will eventually be integrated into our GitHub actions to highlight coverage changes, regressions, or improvements in future PRs.
Use the `test:coverage` script to see the current project coverage. This script will generate a report viewable in the terminal, as well as write a `coverage/lcov.info` file to the project. That `lcov.info` file can then power coverage extensions for VSCode like [Coverage Gutters](https://marketplace.visualstudio.com/items?itemName=ryanluker.vscode-coverage-gutters) or [Code Coverage](https://marketplace.visualstudio.com/items?itemName=markis.code-coverage), allowing us to see code coverage …
=> Add test coverage benchmarking

CONTRIBUTING.md
While following the CONTRIBUTING guide I found I was unable to run the build or test scripts on Node v12 LTS. Installing Node v14 allowed the scripts to run.
=> Add note about Node version in CONTRIBUTING

packages/core/src/defaultInsertMethod.js, packages/core/src/index.js, packages/core/tests/universal-insertMethod.js, packages/core/types/index.d.ts
This PR adds the following:
- Added an `insertMethod` feature that lets users override the default DOM insertion method. By default, a stylesheet will prepend it to the beginning of the document head. Passing `append` changes the insertion method to append it to the end of the document head.
Passing an init function gives the author full control over the dom insertion, which is useful for ShadowDOM wiring up Stitches for a ShadowDOM.
```js
createCss{
// recreates the default insertion method
insertMethod(init) => {
const isAppend = init.insertMethod === 'append'
let currentCssHead = null
let currentCssNode = null
return (cssText) => {
if (typeof document === 'object') {
if (!currentCssHead) currentCssHead = document.head || document.documentElement
if (!currentCssNode) currentCssNode = …
```
=> feat: insertMethod

packages/core/src/createGetComputedCss.js
Apply the fix to the unit-ed property matching regex suggested by @jonathantneal 
Fixes #457
=> fix: change unit-ed property matching regex to exclude line height

packages/core/src/index.js, packages/core/tests/keyframes.js, packages/core/tests/theme.js
This PR fixes an issue with the `keyframes` method, where `@keyframes` rules were not generated correctly. This PR includes tests to ensure the regression does not return.
This PR also includes similar tests for the `theme` method.
Expected usage:
```js
const { keyframes, toString } = createCss()
const fadeIn = keyframes({
'0%': {
opacity: '0',
},
'1%': {
opacity: '1',
},
})
// ... later, somewhere inside or outside of stitches
`animation: 1s ${fadeIn};` // "animation: 1s sxk7pfs;"
// ... the `@keyframes` rule is now also injected
```
=> fix: keyframes expressions

packages/core/types/index.d.ts
This PR fixes an issues where `insertMethod` became required in the configuration typing.
=> fix: issue with insertMethod being required by typing

packages/core/src/index.js, packages/react/src/index.js, packages/react/tests/components.js
A proposed fix for #462, moves the "type determination" concern to the react lib and out of core.
All the tests pass and it works in my medium-sized project, but I'm not 100% sure of all the implications. Feedback appreciated.
=> Fix forward ref components not rendering correctly

package.json, packages/core/src/index.js, packages/react/src/index.js, packages/react/tests/component.js, packages/react/types/index.d.ts
This PR changes how components are processed by `@stitches/core` and `@stitches/react`, fully removing any react component processing from `@stitches/core`, and adding it fully to `@stitches/react`.
See https://github.com/modulz/stitches/pull/467/commits/793b11e6e6ebcd2c1f936265cb01af81631b1da4 for the relevant changes.
Resolves #462
=> Update component processing

packages/core/src/defaultInsertMethod.js
This PR greatly reduces the chances of Stitches updating the DOM, by checking for unique CSS rules _before_ writing updates to a stylesheet.
This can reduce the number of DOM updates by up to 100% when SSR is in also used.
=> Feature: Way Less DOM Updates

packages/core/src/createStringify.js, packages/core/tests/universal-polyfill-prefixed-values.js
This PR adds the ability to automatically prefix the [`fit-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content) and [`stretch`](https://www.w3.org/TR/2020/WD-css-sizing-4-20201020/#sizing-values) values on css size properties in CSS.
**Before**:
```js
{
'.gro': {
width: 'stretch'
}
}
```
**After**:
```css
.gro{width:-moz-available;width:-webkit-fill-available;}
```
**Before**:
```js
{
'.fit': {
width: 'fit-content'
}
}
```
**After**:
```css
.fit{width:-moz-fit-content;width:fit-content;}
```
=> Polyfill prefixed values

packages/core/src/createStringify.js
This PR changes how polyfills are applied, so that polyfills can be replaced by utilities, rather than apply the polyfills after utilities. This will prevent issues where user-authored polyfills create duplicate solutions, or at worst infinite vendor prefixes.
=> Feature: Let utilities override polyfills, do not apply both

.bin/build-package.js, packages/core/src/defaultInsertionMethod.js
This PR changes the default insertion method to reduce the likelihood of style changes.
- During a push of styles, the update to `<style />` is delayed by one frame, tho _only_ if the tag already has content.
- Each push of new changes will restart the delay like a debouncer.
- If a delay to write modified CSS is fulfilled, then `<style />` will be updated.
=> Feature: Updated insertion method

packages/core/src/defaultInsertionMethod.js
This PR changes the default insertion method so that writes are never delayed by one frame, while preserving the recent change to prevent any writing to an SSR’d `<style>` until the page has loaded.
=> Feature: delay-less writes

package.json, packages/core/src/defaultInsertionMethod.js
This PR changes how style insertion works so that SSR styles are not removed until 16 60fps frames have passed since the last dynamic insertion.
=> Feature: background ssr insertion

packages/core/src/index.js, packages/react/tests/component-className-prop.js
Styled elements with `className={undefined}` do not add a class "undefined" to the DOM element anymore.
- resolves #537
=> Fix: Do not add an undefined className to a DOM Element

packages/core/src/Array.js, packages/core/src/StringSet.js, packages/core/src/index.js, packages/core/tests/global-atrules.js, packages/core/tests/universal-tokens.js, packages/stringify/src/Array.js, packages/stringify/src/index.js
This PR updates many stitches internals to allow theme tokens to be used as css property values.
Example usage:
```js
const { global, theme, toString } = createCss({
theme: {
space: {
sp1: '100px',
sp2: '200px',
},
},
})
global({
article: {
marginLeft: theme.space.sp1,
marginTop: theme.space.sp2,
},
})()
expect(toString()).toBe(
`:root{--space-sp1:100px;--space-sp2:200px;}` +
`article{margin-left:var(--space-sp1);margin-top:var(--space-sp2);}`,
)
```
```js
const { global, theme, toString } = createCss()
const mytheme = theme('my-theme', {
space: {
sp1: '100px',
sp2: '200px',
},
})
global({
article: {
marginLeft: mytheme.space.sp1,
marginTop: mytheme.space.sp2,
},
})()
```
Resolves #540.
=> Support theme token values

packages/core/src/index.js, packages/core/tests/component-composition.js, packages/react/tests/component-className-prop.js, packages/react/tests/component-composition.js
This PR updates components so that they will always include their forced composer if none exist.
Resolves #533
Resolves #542
=> Force components to include at least one composer

packages/core/types/css-types.ts
=> fix: autocompletion for `zIndex`

packages/core/src/index.js, packages/core/tests/universal-insertionMethod.js
This PR changes how the configuration object is hydrated, so that the `config` object returned by `createCss` is always the newly hydrated version.
This PR also resolves a regression where `insertionMethod` was not receiving the correct configuration, and includes tests to ensure another regression is unlikely.
Resolves #550
=> Hydrated configuration

packages/core/src/index.js, packages/react/tests/issue-555.js
This PR fixes an issue where non-string `className` prop values were ignored.
Resolves #555
=> fix: support non-undefined className prop values

packages/core/src/createStringify.js, packages/core/tests/issue-999.js
This PR separates "prefixing" from "token prefixing". At this time, Stitches assigns a default `prefix`, which is required to generate valid CSS classes. Authors don’t mind this, but they do mind once the default `prefix` gets assigned to tokens. We are solving this another way — the right way — but as a _patch_ this code creates a **forked prefix just for tokens**, ignoring the default `"sx"` prefix.
This **does not** remove the ability to assign custom prefixes to tokens. The change is limited to the default `"sx"` prefix, and it is only a small, temporary patch.
=> Fix: Ignore the default prefix on tokens

packages/core/src/convert/toHash.js, packages/core/src/features/css.d.ts, packages/core/src/features/css.js, packages/core/tests/issue-450.js, packages/react/tests/issue-450.js
This PR organizes 0.2.x code for the `css` function (and therefore the `styled` function as well). The hope is that the tidier code also means _faster_ code.
=> 0.2.x — cleanup: organize and reduce `css` code

packages/core/src/createCss.js, packages/core/src/createSheet.d.ts, packages/core/src/createSheet.js, packages/core/src/features/css.js, packages/core/src/features/global.d.ts, packages/core/src/features/global.js, packages/core/src/features/keyframes.js, packages/core/src/features/theme.js
This changes the functionality for inserting new rules into the CSSOM so that they will not throw when an invalid rule is being added.
=> 0.2.x — safely wrap css inserts

packages/core/src/createSheet.js
This change updates the internal style insertion method so that it inserts newer, dynamic rules over older, pre-rendered rules.
Resolves #635
=> 0.2.x — Fix hydrated rules inserted in the incorrect order after a reset

packages/core/src/createSheet.js
This change removes the `console.warn` that can display when a dynamically inserted rule is unknown to the browser. In most scenarios, this is because the selector is unsupported in that particular browser, and tho the fallback is also included in the stylesheet, the unsupported rule will still log an unnecessary warning.
Resolves #637
=> 0.2.x — Omit catch warning log on invalid rule

packages/react/src/features/styled.js
This change adds a friendly display name to `styled` components, which can be useful in React Developer Tools and other debuggers.
=> 0.2.x — Add a styled display name

packages/core/src/ThemeToken.d.ts, packages/core/src/ThemeToken.js, packages/core/tests/universal-tokens.js
This change switches `Token#name` back to `Token#token`, as it was in Stitches 0.1.x.
See https://github.com/modulz/stitches/issues/643
=> 0.2.x — rollback `token.name` to be `token.token`

packages/react/package.json
This change expands the `peerDependency` coverage for `react` from `>= 17` to `>= 16`.
Resolves https://github.com/modulz/stitches/discussions/647
=> 0.2.x — Expand `peerDependency` for `react` to include v16

packages/core/src/features/css.js, packages/core/tests/issue-652.js
This PR changes how default variants are spread across compositions, allowing them to spread much more intuitively.
Resolves #652
=> Fix issue with default variants not applying during composition

packages/core/src/createStitches.js, packages/core/src/index.js, packages/core/tests/basic.js, packages/core/tests/theme.js, packages/core/tests/universal-prefix.js, packages/core/tests/universal-serialization.js, packages/core/tests/universal-tokens.js, packages/core/types/index.d.ts, packages/core/types/sheet.d.ts, packages/react/src/index.js, packages/react/tests/universal-serialization.js, packages/react/types/index.d.ts, packages/react/types/sheet.d.ts
This splits `theme` into a `theme` object and `createTheme` function, addressing #684 & #685.
```tsx
import { createStitches } from '@stitches/core'
const { createTheme, theme } = createStitches({
theme: {
colors: {
red: 'Crimson',
},
},
})
const myTheme = createTheme({
colors: {
red: 'Red',
},
})
theme.colors.red
theme.colors.red.value
theme.colors.red.computedValue
theme.colors.red.variable
myTheme.colors.red
myTheme.colors.red.value
myTheme.colors.red.computedValue
myTheme.colors.red.variable
```
---
```tsx
import { createStitches } from '@stitches/react'
const { createTheme, theme } = createStitches({
theme: {
colors: {
red: 'Crimson',
},
},
})
const myTheme = createTheme({
colors: {
red: 'Red',
},
})
theme.colors.red
theme.colors.red.value
theme.colors.red.computedValue …
```
=> Split `theme` into a `theme` object and `createTheme` function

packages/core/src/createStitches.js, packages/core/tests/basic.js, packages/core/tests/component-empty-variants.js, packages/core/tests/component-variants.js, packages/core/tests/global-atrules.js, packages/core/tests/issue-450.js, packages/core/tests/issue-492.js, packages/core/tests/issue-999.js, packages/core/tests/theme.js, packages/core/tests/universal-nesting.js, packages/core/tests/universal-numeric-values.js, packages/core/tests/universal-serialization.js, packages/core/tests/universal-tokens.js, packages/core/types/sheet.d.ts, packages/react/tests/basic.js, packages/react/tests/component-composition.js, packages/react/tests/issue-416.js, packages/react/tests/issue-450.js, packages/react/tests/universal-serialization.js, packages/react/types/sheet.d.ts
This renames the `getCssString` function to `getCssText`.
```tsx
import { createStitches } from '@stitches/core'
const { getCssString } = createStitches()
```
```tsx
import { createStitches } from '@stitches/react'
const { getCssString } = createStitches()
```
=> rename: `getCssString` to `getCssText`

packages/core/src/convert/toSizingValue.js, packages/core/tests/issue-655.js
This fixes the sizing value polyfilling within Stitches, addressing #655.
```tsx
const { css, getCssText } = createStitches()
css({
maxWidth: 'fit-content',
minWidth: 'fit-content',
})()
getCssText()
/*
max-width: -moz-fit-content; max-width: fit-content;
min-width: -moz-fit-content; min-width: fit-content;
*/
```
=> fix: sizing polyfill

.task/build-csstype.js, packages/core/types/css-util.d.ts, packages/core/types/css.d.ts, packages/core/types/theme.d.ts, packages/react/types/css-util.d.ts, packages/react/types/css.d.ts, packages/react/types/theme.d.ts
This PR fixes an issue in v1-canary where numeric types were not always working as expected. Resolves #707.
```ts
import * as Stitches from '@stitches/react'
const { styled } = createStitches({
theme: {
colors: {
red: 'Crimson',
},
},
utils: {
mx: (value: Stitches.PropertyValue<'marginLeft'>) => ({
marginLeft: value,
marginRight: value,
})
}
})
const Styled = styled('div', {
display: 'block',
marginLeft: 5,
mx: 5,
})
```
=> fix: numeric css types

.task/build-csstype.js, packages/core/types/css-util.d.ts, packages/core/types/css.d.ts, packages/core/types/theme.d.ts, packages/react/types/css-util.d.ts, packages/react/types/css.d.ts, packages/react/types/theme.d.ts
This PR fixes an issue in v1-canary where nested styles were not working within custom media. Resolves #705.
```tsx
import * as Stitches from '@stitches/react'
const { styled } = createStitches({
media: {
bp2: '(min-width: 600px)',
hover: '(any-hover: hover)'
}
})
const Styled = styled('div', {
'@media (min-width: 800px)': {
'&:hover': {
color: 'yellow'
}
},
'@hover': {
'&:hover': {
backgroundColor: 'red'
}
},
})
```
=> fix: nested styles within custom media

.task/build-csstype.js, packages/core/types/css-util.d.ts, packages/core/types/css.d.ts, packages/core/types/theme.d.ts, packages/react/types/css-util.d.ts, packages/react/types/css.d.ts, packages/react/types/styled-component.d.ts, packages/react/types/theme.d.ts
This PR fixes an issue in v1-canary where `className` and `selector` were not available on styled components. Resolves #706.
```tsx
import * as Stitches from '@stitches/react'
const { css, styled } = createStitches()
const component = css('div', {})
void component.className
void component.selector
const Component = styled('div', {})
void Component.className
void Component.selector
```
=> fix: issue accessing className or selector on styled components

packages/core/types/stitches.d.ts
fixes: modulz/stitches#713
Check if arg0 is a string (theme class name), if so, include tokens from arg1, otherwise, include tokens from arg0
=> fix: return type for createTheme

.task/build-csstype.js, packages/core/types/css.d.ts, packages/react/types/css.d.ts
This patches the `csstype` package to accept strings on the `zIndex` property.
Resolves #726
=> Fix: Allow string type on `z-index`

packages/core/src/default/defaultThemeMap.js, packages/core/types/config.d.ts, packages/core/types/css.d.ts, packages/react/types/config.d.ts, packages/react/types/css.d.ts
Hi there! Thanks for creating awesome stitches let me can easily build a design system by myself.
I found a little issue and tried to fix it. I added [lineGradient util](https://stitches.dev/docs/utils) into my stitches config and want to apply the gradient color to the border color, it always can't be applied, so I inline gradient color, and it works.
**✅ Works**
```ts
borderImage: 'linear-gradient(to left, #743ad5, #d53a9d)'
```
**❌ Failure**
```tsx
borderImage: 'linear-gradient($primary400)',
```
So I check the source code and guess it be missed in the `defaultThemeMap` config, hope it can be fixed, Thanks!
Signed-off-by: Jie Peng <im@jiepeng.me>
=> fix(defaultThemeMap): add borderImage to default to support colors

packages/core/types/stitches.d.ts
Since `v.1.0.0` the allowed type of `string[]` for `@import` rules was removed from `globalCss`.
The actual functionality remained unchanged, because multiple `@import` rules still work. 
This PR re-adds support for `string[]` types inside `globalCss`.
=> Fix: Allow string array type for global at import rule

packages/core/src/features/globalCss.js, packages/core/tests/basic.js, packages/core/tests/types.test.ts, packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
This PR changes the `globalCss` function to support multiple arguments of global styles. It also updates the types to support this behavior.
Resolves https://github.com/modulz/stitches/issues/758
=> Support n composition in `globalCss` function

packages/core/types/index.d.ts
This fixes the error `Type 'unique symbol' cannot be used to index type 'Component'.` when trying to build a TypeScript app, addressing https://github.com/modulz/stitches/issues/754.
=> fix: VariantProps symbol type error

packages/react/types/index.d.ts
This fix applies the same fix from https://github.com/modulz/stitches/pull/757 to the react package.
=> fix: Apply symbol type fix from core to react

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
This resolves a TypeScript issue where multiple styles passed into `globalCss` throw a typing error.
Resolves https://github.com/modulz/stitches/issues/794
=> Fix TS issue with globalCss

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
This PR fixes JSDoc annotations for `compoundVariants` property.
=> fix: jsdoc annotation for `compoundVariants`

packages/core/src/convert/toPolyfilledValue.js
This pull request adds the necessary polyfill for [`mask-size`](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-size).
Resolves https://github.com/modulz/stitches/issues/790
=> Add mask-size polyfill

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts, packages/test/Issue-803-core.ts, packages/test/Issue-803-react.ts
This change fixes an issue typing `@import` and `@font-face` rules in `globalCss`.
This resolves https://github.com/modulz/stitches/issues/803
=> Fix issue typing import and font-face rules

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
This change fixes an issue with the typing for the default theme, exposing `className` and `selector`, which are otherwise available on any theme created with `createTheme`.
This resolves #781
=> Fix issue with default theme typing

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
This PR fixes an issue with typing `compoundVariants`.
It resolves https://github.com/modulz/stitches/issues/786
=> Fix issue with compound variant typing

packages/react/tests/types.test.tsx, packages/react/types/util.d.ts
Fixes #821 by adding support for components with union prop types.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types
=> Add distributive condition to `Assign` util

packages/core/src/convert/toCssRules.js, packages/core/tests/issue-788.js
This fixes an issue with using utils that share the same name as a selector.
Resolves https://github.com/modulz/stitches/issues/788
=> Fix an issue with utils named like selectors

packages/core/types/index.d.ts, packages/react/types/index.d.ts, packages/test/Issue-813-core.ts, packages/test/Issue-813-react.ts
Related #813 
/cc @raunofreiberg
=> Update `PropertyValue` and `ScaleValue` types to support config

packages/react/types/index.d.ts, packages/test/Issue-813-react.ts
=> Fix TS `PropertyValue` and `ScaleValue` types in the react package

packages/core/src/features/css.js, packages/core/src/sheet.js, packages/core/tests/basic.js, packages/core/tests/component-css-prop.js, packages/core/tests/component-empty-variants.js, packages/core/tests/component-variants.js, packages/core/tests/issue-450.js, packages/core/tests/issue-492.js, packages/react/src/features/styled.js, packages/react/tests/component-css-prop-react.js, packages/react/tests/component-css-prop.js, packages/react/tests/component-variants.js, packages/react/tests/issue-416.js, packages/react/tests/issue-671.js, packages/react/tests/issue-737.js
Fixes #737 by giving responsive variants and non-responsive variants different injection buckets instead of sharing the same one
Fixes #671 by making sure that a stitches component that wraps some another react component is going to defer the injection until after the inner component is rendered
Keeping it as a draft as I would like to merge this myself after the review as I would like to get #869 in first and then get this in as there is an area in this PR that would need an update after #869 is merged
=> improve injection order

packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts
Simple fix to address the typing issue in #878; the offending type could be of types beyond `string | number`, so I added a type guard.
CC: @dlehmhus
=> 878: Fixed issue with ThemeTokens typing

packages/core/src/sheet.js
Migrating from Emotion to Stitches, I ran into issues with an older iOS environment.
The cause is as described at https://github.com/modulz/stitches/issues/756
However, some old browsers assign null instead of throwing a `SecurityError` on the accessing `cssRules`.
=> improves compatibility with inconsistent CSSOM behavior of older browsers

packages/core/src/sheet.js
At my workplace, some of the users reported that the whole app gets unresponsive, only when they're using MS Edge browser.
Turns out, it was similar situation with what [this StackOverflow question](https://stackoverflow.com/questions/56479576/i-got-the-expected-script1005-with-javascript-on-edge-with-chrome-its-wor) describes. That is: some versions of MS Edge does not allow `catch` clause if there's no exception identifier (`(e)` part), and just throws `SCRIPT1005` error.
I'm not sure what exact version range of MS Edge has this issue. Nevertheless, I think this change might not hurt anyone and hopefully save someone's few hours.
=> fix: Specify missing exception identifier in `addApplyToGroup`

packages/core/src/sheet.js, packages/core/tests/issue-908.js
This PR addresses https://github.com/modulz/stitches/issues/908.
There was not tooling for tests with DOM API mocks, so I wrote a minimal one.
=> Fix for #908: toString in hydrated group sheet

package.json, packages/core/types/stitches.d.ts, packages/react/types/stitches.d.ts, packages/test/package.json
Fixes #947.
TypeScript 4.6 changed... something... that necessitated checking `string extends Composers[K]` in addition to `Composers[K] extends string` to filter out string-assignable types.
This error actually surfaces in `test/build-types/built-types-test.tsx` if you switch to TS 4.6, but it looks like those types are generated manually based on published Stitches versions, so I didn't touch them in this PR.
=> Fix "length is declared here" issue with TS 4.6

.gitignore, packages/core/src/sheet.js, packages/core/src/utility/getNonce.js
When trying to enforce strict rules about which content is allowed on a specific page, a Content Security Policy (CSP) is the way to go.
The Stitches library currently injects all of their style scripts as an inline style to the DOM. For this to function, a CSP would need to contain `style-src: unsafe-inline` for the app/library to function properly. As the attribute name implies, this is unsafe and not the recommended way of building a secure app.
There is the concept of nonce attributes that allows inline style/script tags to be executed if the nonce matches the CSP header. The rule would look something like this `style-src: 'self' 'nonce-<injected-id>'` If Stitches checks for and sets this nonce, security minded apps can get rid of the unsafe-inline setting and consume this library. …
=> feat(security): add nonce support for injected style tags

packages/core/types/config.d.ts, packages/core/types/css-util.d.ts, packages/core/types/index.d.ts, packages/core/types/stitches.d.ts, packages/core/types/styled-component.d.ts, packages/react/types/config.d.ts, packages/react/types/css-util.d.ts, packages/react/types/index.d.ts, packages/react/types/stitches.d.ts, packages/react/types/styled-component.d.ts
fixes type module resolution for NodeNext/ESM in TypeScript
fixes #1084 
TypeScript requires `.d.ts` files to follow ESM module import rules as well, so these files needed extensions added to imported local modules so that types can be resolved when Stitches is used in a project that has `moduleResolution: 'NodeNext'`.
=> add .js extension to .d.ts files (TS NodeNext fix)

packages/core/tests/issue-921.ts, packages/core/types/css-util.d.ts, packages/react/tests/issue-921.tsx, packages/react/types/css-util.d.ts
When util's and property's names clash the util's type should take precedence.
Fixes #921
BTW type testing doesn't seem to work, the tests will pass regardless of the typing.
=> Fix CSS type for utils overshadowing properties
